// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcadclsgekjzqfibezyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjYWRjbHNnZWtqenFmaWJlenlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNzgwNjQsImV4cCI6MjA2NDc1NDA2NH0.oQ0Dfk-td9FgsnWnoSABW9Dg7MoGk4ktNr3NdPN_sp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);